### ISSUE TITLE
Time tracker not work

### ISSUE THREAD

**Issue by Ninoh-FOX** [OnionUI/Onion#576]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

Time game list is always is empy.

### Steps to Reproduce

Launch any game

### Provide any additional context or information that may help us investigate your issue

The script for launch the emulators has the line for activitytime. I don't know if this is old, but in 3.x worked fine.

**Comment by Ninoh-FOX** [comment]
Fixed, I was add **manually** the file and directory mnt/SDCARD/Saves/CurrentProfile/saves/playActivity.db and now work again
