### ISSUE TITLE
Activity Tracker Doesn't Handle Period/Dots in Game Title

### ISSUE THREAD

**Issue by cuteseal1** [OnionUI/Onion#578]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

When viewing the Activity Tracker, ROMs that have periods / dots / full stops in their file names are not displayed correctly.
The game names are truncated from the last period / dot / full stop onwards.

For example:
```
 01. S.T.U.N. Runner = 01. S.T.U.N
 02. Chrono Trigger = 02
 03. Ms. Pacman = 03. Ms
```

### Steps to Reproduce

1. Put ROMs with periods / dots / full stops in their filename in the ROMs folder
2. Open ROMs and play
3. View Activity Tracker

### Provide any additional context or information that may help us investigate your issue

<img src="https://user-images.githubusercontent.com/115526626/195464067-4121263b-517f-4624-b1a8-113d75ed376a.jpg" width="340">

**Comment by Olywa** [comment]
There appears to be a little more to this than just names being truncated after a period as if you look at my example (last game), that's not happening for me. We've also not seen this reported before so I'm wondering if there is something unique going on with your setup.

![PlayActivity_001](https://user-images.githubusercontent.com/98862735/195779785-3cd1e839-d5ce-43a2-815d-86e86299736d.png)

**Comment by cuteseal1** [comment]
Thank you very much for looking into this. Very interesting.  It so happens I got a new micro sd card today so I did:

1.  A fresh install of onion os
2. Copied my /roms and /saves over
3. In package manager, uninstalled and re-installed the Activity Tracker app
4. Deleted the /saves/playactivity.db file
5. And it looks like it is still happening

All the roms are from the platform explorer pack on reddit. As far as I can tell I can’t see any other special characters in the file name. 

I have also checked that there is no miyoogamelist.xml file in the folder. 

![569E8327-B995-4C48-AB75-10400C732B24](https://user-images.githubusercontent.com/115526626/195849303-3d58d294-6a2b-4afe-8f14-cd8bb8eab857.jpeg)
![D0295EA9-8F3D-4247-93F3-D445D724D3A8](https://user-images.githubusercontent.com/115526626/195849349-3fd57445-c18c-4f24-9533-f8d578706a6c.jpeg)
![8909620C-704E-411A-806D-19300B55F4F9](https://user-images.githubusercontent.com/115526626/195849360-5638677e-077e-4b36-8339-ddcd26d20d9d.jpeg)

**Comment by cuteseal1** [comment]
If you would like to test / this particular file is in the Super Nintendo pack - download link is in row 34:

https://docs.google.com/spreadsheets/u/0/d/1qe3vRUXWJxlsztp21Fpmq-yyWNdo-SzDl4i_PSkzbM0/htmlview

what is unique about this rom pack is that they have compiled the top 100 games for each platform and have named them in order so all the names start with 01. 02. 03. etc. 

Please let me know if there is anything else you would like me to test.

**Comment by Olywa** [comment]
Hi there, I have removed the links to roms in your post, that is not permitted here (we do not want to bring legal troubles to the project). 

With that out the way, thanks for all the info, it's useful - we will look a little further into what is happening.

**Comment by Olywa** [comment]
@cuteseal1 
OK, I've just done some testing myself and have **confirmed this issue**.
It appears to be system and extension agnostic (I tested with SNES and GBA), using several formats (7zip, zip, sfc, gba). 
It also does not matter whether there is a space or text immediately after the period.
<img src="https://user-images.githubusercontent.com/98862735/195962782-239a0421-dda9-44fd-9901-bc45c7ae8bfe.JPG" width="500">
<img src="https://user-images.githubusercontent.com/98862735/195962773-c139d369-5073-4746-b51b-76a140409918.png" width="300">  <img src="https://user-images.githubusercontent.com/98862735/195962775-d7425126-3cb1-4315-9bd4-e2ca0e3c796c.png" width="300">

This doesn't explain why Mario vs. Donkey Kong (GBA), per my earlier example, displays correctly 🤷‍♂️

@Aemiii91 I've done all I can, with you for investigation 😉

**Comment by Olywa** [comment]
@cuteseal1 This will be investigated but until a solution is identified and released and in order to resolve immediately in your case, I have prepared two Windows scripts to batch edit your rom names which you can use as a workaround...

- The first replaces periods immediately followed by a space, with two spaces (to make it easier to reverse). 
- The second undoes this action (replacing two spaces with a period and space to return everything to how it was. 

[Batch Scritps to remove periods.zip](https://github.com/OnionUI/Onion/files/9790996/Batch.Scritps.to.remove.periods.zip)

**Note**: You will need to edit the path `A:\0-TEMP DOWNLOADS\rom test\` in the batch script (with a text editor like notepad) to replace the path for your actual rom path. If you are not worried about reversing later then you can also edit `set "space=  "` (from two spaces to be just one space).

Maybe do a test with one system first. There will be the odd game that you may have to edit manually (like S.T.U.N. Runner) but it should be good for the majority.  

The issue will remain open until a proper solution is found/implemented.

**Comment by cuteseal1** [comment]
Thank you Olywa for confirming - I’m glad I’m not the only one!

And I appreciate the workaround. Hopefully a proper fix is not far off.

**Comment by Aemiii91** [comment]
We no longer strip everything after the last dot in the next release.

**Comment by cuteseal1** [comment]
Thank you! Looking forward to the next release!
